### ISSUE TITLE
RFC For VVGO tokens

### ISSUE THREAD

**Issue by jacksonargo** [virtual-vgo/vvgo#101]
I played around with oauth this weekend, and I think I've figured out what we need to do.

All this in support of authenticating our website users via the user's role on our discord server. (Discord api docs call these servers guilds). 

## Login

1. We need the users discord ID. Discord OAuth allows us to get a temporary auth token to assume the users discord identity and query for that users user id. (More details in the Oauth section).

2. With the discord ID, we can use our own internal token to query Discord for the users roles on our discord guild.

3. If the user has the role 'VVGO Member`, they are authenticated and get a signed session cookie. (More details in the cookie section). Sessions are stored as a map of session key to discord user info.

## After login

1. Api server validates the cookie hash. If the cookie hash is valid, continue, else `please login`.
2.  If the cookie is expired, the api server will lookup the discord user id from the sessions map. Then, query discord using our internal token to validate that the users still has the correct roles in our discord guild. If this is still true, then we can assign a new cookie with updated expiration. Else `please login`.
3. The server will check the session map to validate the session id still points to a user.
3. The user has authenticated and can access the site.

## Logout

1. To logout an authenticated vvgo user, the api server deletes the session id provided in the user's token from the session map.

## How OAuth works for vvgo:

Discord oauth allows us to assume the website user's discord identity in order to query for that users discord id. 

1. We need the _request access_ link for users to access our website. We can put this link in a `login with discord` button on the website. This link directs users to the discord login page. Discord asks them if vvgo is allowed to see their discord identitiy. 
This link looks like: `https://discordapp.com/api/oauth2/authorize?client_id=700963768787795998&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth_discord&response_type=code&scope=identify`

1. If the user accepts, discord redirects them to our server using a link we configured in discord.

This redirect link looks like: `http://vvgo.org/oauth_discord?code=access_code_given_by_discord`

2. We use the code provided in the redirect and the vvgo discord app's api key to query discord for the users token with Identity priv. This allows us to get the users' discord id.

## Session tokens are signed and validated

Our session tokens will contain the following data:
* Hash - sha256sum of the session data and our internal secret.
* SessionID - uint64 crypto-random generated id.
* ExpiresAt - timestamp

The sum is calculated on a string concat of `our secret`+`session id`+`expires`.

The serialized session token looks like: 
```
|-----------hash-stored-as-four-uint64-strings------------------------------|-session_id---|-expiry nanos--|
efc691b4e7b839e1-V-b5d412436dc4119b-V-b2e0dbf93cf52bb7-G-bcf63f4fdd4adf89-O-7b7cc95133c4265d1607717a7c5d32e1
```
* I added the vvgo for style :) *

These session tokens are stored in an http cookie called `vvgo-sessions`.

When we receive a request with the vvgo-sessions cookie, we can recalculate the hash with our secret. If the hashes do not match, the cookie is invalid.

## User data
We only need to store the discord user ids, since we can use our own token to validate that the user id is on our vvgo discord guild. _No personal identifiable info will be stored by VVGO!_

Each session id maps to a user data object. User data is stored internally in a coroutine safe map in memory, and externally in object storage serialized as json.

The user data objects look like this:

```golang
type UserType int

const UserTypeDiscord UserType = 1

type User struct {
    UserType
    DiscordUser
}

type DiscordUser struct {
    UserID string
    VVGOGuildRoles []string
}
```

**Comment by 0az** [comment]
I will note that I have a half-finished prototype for this, using JSON Web Tokens - specifically, the Signature spec. For all of the *bad* things about JWS, the limitations and footguns are very well understood - well, at the very least, *I* understand them, after a couple weeks meditating on the topic.

I recommend the following implementation: https://github.com/square/go-jose.

Granted, we should just use Redis. I don't have it ported over to Redis yet, but regardless my work on anti-CSRF should be usable.

---

### Cross Site Request Forgery / CSRF (OAuth2 State Parameter)

To harden against CSRF, we use the standard OAuth2 `state` parameter.

The `state` parameter MUST be associated with exactly one user attempt. My stateless implementation works with *three* pieces of information:

- `key`: A server side cryptographic secret
- `raw`: A *token* with a minimum of 64 bits of secure randomness. The final implementation MAY also consistently attach an expiration timestamp and not-before timestamp. As this is a *pre-session* token, there is no other meaningful identifier to attach.
- `hashed`/`state`: `HMAC_SHA256(value = raw + b'csrf', key = key)`

There are *three* involved parties, notated like so:
- **User**: The user making the OAuth2 request. We do not control this.
- **Client**: The OAuth2 client. We control this.
- **Service**: The OAuth2 service, probably Discord. We do not control this.

On an OAuth2 request from a **User**, the **Client** computes a value for `raw` and `hashed`. The **Client** attaches `raw` to the **User** using a Cookie, and MAY do so using a JWS or some other tamper-proof method.

The **Client** generates an authorization URL for the **Service**, with `hashed` as the `state` parameter.

The **Client** sends a `302 Found` redirect to the **User** to the **Service** with `raw` stored in a *Cookie*, or some other tamper-proof storage.

The **Client**'s OAuth2 `/callback` finds the given **User**'s value for `raw`, recomputes `hashed` using the fixed keyed-hash algorithm, and compares against the `state` parameter.

---

The following Header/Payload standards apply to all 

### Header (Public-Asymmetric)

The header MUST have exactly the following case sensitive fields and values:
- `alg`: `ES256`

If the header does not match these values exactly, the token MUST be treated as invalid.

### Header (Localized-Symmetric)

The header MUST have exactly the following case sensitive fields and values:
- `alg`: `HS256`

If the header does not match these values exactly, the token MUST be treated as invalid.

### Payload

All non-bare JWS payloads SHALL contain the following claims:

- `iat`: Issue time (POSIX timestamp).
- `nbf`: Not before.
- `exp`: Expiration time.

If the current time falls before `nbf` or after `exp`, the token MUST be treated as invalid.

`nbf` SHOULD be the same as `iat`. `exp` SHOULD be no more than ten minutes (600 seconds) past `nbf`.

#### Authentication Service Payload

- `discord-uid`: Discord User ID
- `vvgo-member`: Boolean indicating if VVGO member.

The **Authorization** service MUST NOT emit a JWT if `vvgo-member` is false, and should instead return `403 Unauthorized`. This **Authorization** failure SHOULD be logged (including Discord User ID and Discord Username), for support purposes.

**Comment by jacksonargo** [comment]
Oh perf!

If I understand correctly, JWT's work similar to cookies, in that they are sent with every request. With JWT, the signature is part of the document itself, unlike with cookies (where we encode the signature in the value string). 

So, cookies/jwt's whatever we choose, should plugin into the session storage rfc nicely.

For the jwt payload, we only need the int64 session id. With the session id, we can lookup all the info we need in our own user objects db.

**Comment by 0az** [comment]
> For the jwt payload, we only need the int64 session id. With the session id, we can lookup all the info we need in our own user objects db.
Is the user objects db going to be Redis? I'd prefer that, if possible.

Regardless, JWT is only necessary if we were trying something without a common state store. As we have Redis, we can use that.


> ## Session tokens are signed and validated
> 
> Our session tokens will contain the following data:
> 
>     * Hash - sha256sum of the session data and our internal secret.
> 
>     * SessionID - uint64 crypto-random generated id.
> 
>     * ExpiresAt - timestamp
> 
> 
> The sum is calculated on a string concat of `our secret`+`session id`+`expires`.
> 
> The serialized session token looks like:
> 
> ```
> |-----------hash-stored-as-four-uint64-strings------------------------------|-session_id---|-expiry nanos--|
> efc691b4e7b839e1-V-b5d412436dc4119b-V-b2e0dbf93cf52bb7-G-bcf63f4fdd4adf89-O-7b7cc95133c4265d1607717a7c5d32e1
> ```

Anyway, I'm not sure if there's a point in the hash - it does nothing against Session ID copy attacks.

Similarly, we can drop the expiry. Just set Redis to expire the session key.

**Comment by jacksonargo** [comment]
We wont be storing sessions in redis. At least, not for now. We're only running a single container of the webapp, so sessions will be stored in mem.

**Comment by jacksonargo** [comment]
The signing hash protects against modified cookies. 

If I send you a cookie like `session=1` and you send me back a cookie `session=2`, I have no way of knowing if you modified that data.

If I attach a signature, then if you send me `session=2` the signatures wont be the same, and I'll know the data has been modified.

**Comment by 0az** [comment]
I'm not sure how much protection that adds, though.

I guess it can't hurt. Defense in depth.

**Comment by jacksonargo** [comment]
re: anti-CSRF

Oh ok I get it now. I didn't realize what the state param was for until now. I was thinking about the session cookies for _after_ authentication is done, but not for this use case.

Your design is :+1: I see no need for redis.

**Comment by 0az** [comment]
Remaining hole is message format. Currently considering the following:
```
unprotected = raw + '.' + timestamp()
protected = unprotected + '.' + hmac(unprotected)
```

### RFC Errata

The RFC did not specify the cookie to be used. The cookie used for CSRF state SHALL be named `vvgo-csrf-state`, and must be appropriately restricted, including a short expiration time of no more than five minutes (300 seconds).

In addition, the RFC originally stated that the timestamp was optional. The `raw` state itself now SHOULD NOT include a timestamp.
