### ISSUE TITLE
Write backup task to backup Redis

### ISSUE THREAD

**Issue by 0az** [virtual-vgo/vvgo#112]
Backup Redis DB file from Persistent Volume Claim to Object Storage. Dockerization is not necessary. Pull request should be against the vvgo-infra repo. If you need access, ping @jacksonargo.

Potential solutions:
- Derive from https://hub.docker.com/r/curlimages/curl and write a bash script. Resource: either @0az or @jacksonargo.
- Derive from https://hub.docker.com/r/rclone/rclone and write a bash script. Resource: either @0az or @jacksonargo.
- Dockerize a Python script. Resource: @0az.
- Dockerize a Golang command. Resource: @jacksonargo.

**Comment by jacksonargo** [comment]
no longer need to backup redis. data is backed in google sheets.
