### ISSUE TITLE
Participant data to collect upon submitting audio/video

### ISSUE THREAD

**Issue by Ranzha** [virtual-vgo/vvgo#114]
On the eventual /upload page, the following data should be collected regarding the participant's submission:

- **Project:** a dropdown menu, alphabetically sorted, with items such as ```01-snake-eater```, ```02-proof-of-a-hero```.
- **Part Name:** a searchable dropdown menu, sorted alphabetically or in score order (#98), with items such as ```Flute 1```, ```Violin 2```.
- **Your Name:** a short text field. This must include a message akin to 'if you wish to be credited by a different name, enter that instead'.
- **Instrument:** a searchable dropdown menu, sorted alphabetically or in score order (#98), with items such as ```Horn in Eb```, ```Kulintang```.
- **This file is my submission for:** with two checkboxes, labelled ```Audio``` and ```Video```.
- **Email address:** short text field. This must include a message akin to 'We won't use your email for anything except for sending you updates on VVGO projects'.

**Comment by jacksonargo** [comment]
I'm gonna be super critical about any personal data we store. We'll need a privacy policy as well, explaining why we want this info and where we might share it.

What do you have in mind with emails?

**Comment by Ranzha** [comment]
As it currently stands, I'd only want to use email addresses to:
* Send confirmation emails for uploads
* Notify people of addenda to open projects (e.g. deadline changes, supplemental materials)
* Notify people of new projects as they're opened for submissions
* Send "Thank You" after the submission deadline with rudimentary qualitative stats on the submissions we received
* Share finished audio/video releases

**Comment by jacksonargo** [comment]
I think we've resolved this in other places, so closing this issue.
