### ISSUE TITLE
Implement sessions

### ISSUE THREAD

**Issue by jacksonargo** [virtual-vgo/vvgo#12]

**Comment by 0az** [comment]
Relevant:
- https://github.com/alexedwards/scs
- https://github.com/gorilla/sessions

Leaning towards `alexedwards/scs`.

**Comment by 0az** [comment]
As we have migrated to k8, we now have the ability to use Redis for non-cache, non-ephemeral content.

**Comment by 0az** [comment]
Closing in favor of #8.
