### ISSUE TITLE
We're getting timeouts from cloudflare, and we need health checks!

### ISSUE THREAD

**Issue by jacksonargo** [virtual-vgo/vvgo#135]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by jacksonargo** [comment]
I added the checks and increased replica count to 3.

**Comment by 0az** [comment]
Do we know what's causing the timeouts?

**Comment by jacksonargo** [comment]
Not sure yet. My honeycomb subscription ran out so now we need a new tracing db :cry:

**Comment by 0az** [comment]
Do we have logs from Cloudflare or the API server?

**Comment by jacksonargo** [comment]
The server logs are just going to stdout on the kube containers, so they are lost after each deployment.
I checked cloudflare, but they don't have any logs either.

**Comment by jacksonargo** [comment]
I'm honestly not too worried about it right now.
