### ISSUE TITLE
Project Pages

### ISSUE THREAD

**Issue by Ranzha** [virtual-vgo/vvgo#183]
Jackson brought this up months ago, but we should have a page for each project!
Now that the Snake Eater video is off the homepage, it's nowhere on the site.

These can be modeled after [Video Games Live](https://www.videogameslive.com/media/) and [Eric Whitacre's Virtual Choir](https://ericwhitacre.com/the-virtual-choir/history/vc1-luxaurumque).
Seems we'd need a big ol' YouTube embed, a Bandcamp embed, stats, credits, and textual info about each project.

**Comment by RatchetOfVaporex** [comment]
Should the textual info be a small blurb/program note about the piece? What are we looking for there? Everything else here sound like a good idea though!

**Comment by jacksonargo** [comment]
Oh buddy another finished!
