### ISSUE TITLE
Wintry Mixtape Nice to haves

### ISSUE THREAD

**Issue by jacksonargo** [virtual-vgo/vvgo#329]
* Way for people to submit host interest form. We have a google form already.
* Dashboard for ED's to see the submissions and approve them.
* Approval workflow:
    * Message mixtape host that they have been approved | Include how to access the dashboard
    * Create a channel
    * Give the project host the role `MixtapeHost`
    * Add them to the channel.
* Dashboard allows project hosts to: (projects have multiple owners, owners can modify any of their projects)
    * Edit Project name, blurb, links to material, recording deadline.
    * Add people to their channel.
* Dashboard for members to view all of the approved mixtape projects.
   * Search projects
   * View all of them at once.

**Comment by Ranzha** [comment]
Maybe too difficult to implement, but:
* Dashboard allows project hosts to add instrumentation
* Dashboard for members allows users to query by instrument

Bot to deliver welcome message to new members who join a project channel via host-submitted add-members form.

**Comment by jacksonargo** [comment]
Priorities are host dashboard and members dashboard.

**Comment by jacksonargo** [comment]
I'm going to close this ticket since we've already made our release for this. The remaining action item is already in https://github.com/virtual-vgo/vvgo/issues/323
