### ISSUE TITLE
Setup Codecov

### ISSUE THREAD

**Issue by 0az** [virtual-vgo/vvgo#33]
#### Resources

- https://docs.codecov.io/docs
- https://github.com/codecov/codecov-action

**Comment by jacksonargo** [comment]
:heart: I was wondering if we would want to do this or not.

**Comment by jacksonargo** [comment]
This is for code-coverage and static analysis stuff?

**Comment by 0az** [comment]
Yeah. Not 100% necessary, but good to have.

**Comment by jacksonargo** [comment]
Not necessary, but so much fun!

**Comment by jacksonargo** [comment]
wont do
