### ISSUE TITLE
Overhaul follow-up

### ISSUE THREAD

**Issue by Ranzha** [virtual-vgo/vvgo#335]
There are a few effects of the overhaul that should be fixed after Wintry Mix stuff is handled:
- [x] [/projects](https://vvgo.org/projects/) shows projects that have the "Hidden" tag, namely End Cards and the April Fools 2021 joke project. To fix this temporarily, I've set "Parts Released" to "False" for all these.
- [x] Project pages were once accessible via permalink (e.g. [this](https://vvgo.org/projects?name=13-false-knight)), and these are now missing. Externally, permalinks are nice to share individual projects with people without needing to link the YouTube video. Internally, permalinks are nice to test credits before they're made public.
- [x] On /projects, submission deadlines are visible for all projects, but shouldn't be if "Video Released" is true.
- [x] The title of /projects and /credits-maker is "VVGO | Parts", oopsieeee

**Comment by jacksonargo** [comment]
Wooh! I think I got all these!
