### ISSUE TITLE
Minify assets at build time

### ISSUE THREAD

**Issue by jacksonargo** [virtual-vgo/vvgo#34]
Not sure if this is something we actually _need_ to do, but maybe something to consider.

**Comment by 0az** [comment]
I'd personally swap the data table implementation first, since that's the bigger gain IMHO.

**Comment by jacksonargo** [comment]
p95 for assets is <2ms. So this is totally unnecessary.

![Screenshot from 2020-04-23 18-22-36](https://user-images.githubusercontent.com/7391437/80165061-6df7df00-858f-11ea-9cd0-ddfc256fde3e.png)
