### ISSUE TITLE
Need a page cache

### ISSUE THREAD

**Issue by jacksonargo** [virtual-vgo/vvgo#41]
I can't think of a better page cache and proxy than nginx.

Unless you wanna go varnish. But I don't... haha

**Comment by 0az** [comment]
My 2¢ is Caddy, because it's absurdly easy to set up. Also, I've used it in my other projects, so I'm much more familiar with it.

**Comment by jacksonargo** [comment]
I've never used Caddy, so I'm down to try it. And, it's written in golang! So, I'm even more interested.

But these docs make me wanna kms. I just want a list of directives omg

**Comment by jacksonargo** [comment]
But I found what I needed, so caddy it is.

**Comment by jacksonargo** [comment]
omfg this is so annoying 
>The data directory must not be treated like a cache. Its contents are not ephemeral or merely for the sake of performance. Caddy stores TLS certificates, private keys, OCSP staples, and other necessary information to the data directory. It should not be purged without an understanding of the implications.
>It is crucial that this directory is persistent and writeable by Caddy.
https://caddyserver.com/docs/conventions#data-directory

But what are the implications? What is the other _necessary information_ that's stored there?

**Comment by jacksonargo** [comment]
>TLS certificates, private keys, OCSP staples
We wont be storing any of this stuff, so I don't care if it's gone.

**Comment by jacksonargo** [comment]
Honestly tho, if this is doing some weird storage thing and needs persistent data, then it really doesn't fit our use case.

**Comment by 0az** [comment]
Closing, NGINX.
