### ISSUE TITLE
Bulk sheet music and click tracks upload

### ISSUE THREAD

**Issue by jacksonargo** [virtual-vgo/vvgo#51]
We'll parse the data fields from each individual file name.

File names look like: `Human-Readable-Info-[part name, part name, part number, part number].pdf`

The data between the brackets contains the machine readable info as comma separated values.
Anything that can be converted into an integer is assumed to be a part number.
Everything else is a part name.

When the files are posted, the api should:
 * validate that the files names contain at least one part number and one part name.
 * show the uploader all the data that was inferred from the file names
 * highlight any new instruments/part names that the db hasn't seen before. This allows the uploader to spot check for any accidental misspellings.
 * highlight any files that could not be validated so the uploader knows to fix and try uploading again.

For example, we might receive:
```
Flute 1 [flute, 1].pdf
Flute 2 [flute, 2].pdf
Piccolo [piccolo, 1].pdf
Oboe 1 [oboe, 1].pdf
Oboe 2 [oboe, 2].pdf
Clarinet 1 [clarinet, 1].pdf
Clarinet 2 [clarinet, 2].pdf
Bassoon 1 [bassoon, 1].pdf
Bassoon 2[bassoon, 2].pdf
Horn in F 1 [horn in f, 1].pdf
Horn in F 2 [horn in f, 2].pdf
Horn in F 3 [horn in f, 3].pdf
Horn in F 4 [horn in f, 4].pdf
Trumpet 1 [trumpet, 1].pdf
Trumpet 2 [trumpet, 2].pdf
Trumpet 3 [trumpet, 3].pdf
Trombone 1 [trombone, 1].pdf
Trombone 2 [trombone, 2].pdf
Trombone 3 [trombone, 3].pdf
Tuba [tuba, 1].pdf
Timpani [timpani, 1].pdf
Percussion 1 [percussion, xylophone, tubular bells, 1].pdf
Percussion 2 [percussion, snare, tam-tam, bass drum].pdf
Percussion 3 [percussion, piatti, crash cymbals, syspended cymbal].pdf
Harp [harp, 1].pdf
Piano [piano, 1].pdf
Violin 1 [violin, 1].pdf
Violin 2 [violin, 2].pdf
Viola [viola, 1].pdf
Cello [cello, 1].pdf
Contrabass [upright bass, 1].pdf
Chorus [choir, soprano voice, alto voice, tenor voice, bass voice, 1].pdf
Chorus [alto voice, bass voice, 2].pdf
```

**Comment by jacksonargo** [comment]
Things to consider:
* What's the largest request we're willing to handle? (bigger payloads mean bigger mem usage)

**Comment by 0az** [comment]
> Things to consider:
> 
>     * What's the largest request we're willing to handle? (bigger payloads mean bigger mem usage)

We'll probably end up splitting this into individual uploads on the client side, so we don't flood the server. Also, we'll probably want to change up the API to match. Now, the question is, now that we have a UI dev, do we want to offload more to UI? Rich UI + api support? Or do we want to go with more on the backend.

API BIkeshed: 
```
Prefix: /api
POST: /projects/:project/part/:part/sheet
- Upload a sheet. Body: application/pdf.
POST: /projects/:project/part/:part/click
- Upload a click track. Body: audio/*, though we'll probably want something that's web compatible for browser play.

:project - str
:part - int
```
As all necessary data is encoded in the filename + route pair, and client side validation needs to be mirrored on the server, we can get away without using `multipart/form-data` or something more esoteric - keep it simple.

Pre-post edit: tomorrow we should discuss client/server split.

**Comment by Ranzha** [comment]
Individually uploading 60+ files will be a huge pain for specifically me though :P

**Comment by jacksonargo** [comment]
I'm thinking we use js to parse the file names, batch up the payloads, and make the requests.
JS can serialize the request as a json array with required fields for each pdf.
Something like:
```json
[
  {
    "original_file_name": "...",
    "part_numbers": [1, 2],
    "part_names": ["trumpet", ... ],
    "pdf_bytes": "base64 encoded bytes...",
  },
]
```

**Comment by jacksonargo** [comment]
I hate to be this way, but I'll never agree to an api like this:
```
POST: /projects/:project/part/:part/sheet
- Upload a sheet. Body: application/pdf.
POST: /projects/:project/part/:part/click
- Upload a click track. Body: audio/*, though we'll probably want something that's web compatible for browser play.
```

**Comment by jacksonargo** [comment]
Rather than encoding fields in the url, we should encode them in json or a structured doc like protobuf that has well typed fields and field names.

**Comment by jacksonargo** [comment]
Started outlining this in pr #53

**Comment by jacksonargo** [comment]
The more I think about it, the more I like the idea of using protobuf between js client and api server. I'm saying we use grpc. Proto over http is perfectly valid.
But, with protobuf, we'll effectively have all the client->server encoding autogenerated for us, and all we need to do is populate the documents.

**Comment by jacksonargo** [comment]
@Ranzha How comfortable are you on the command line? We could also just build a cmdline tool do that makes the upload requests and skip the whole web interface all together. Probably would be faster that way.

**Comment by jacksonargo** [comment]
We've got object storage now, so binary distribution wont be hard.

**Comment by 0az** [comment]
> Individually uploading 60+ files will be a huge pain for specifically me though :P
Oh, no. The endpoint is individual, but the form would handle sending them sequentially.
> The more I think about it, the more I like the idea of using protobuf between js client and api server. I'm not saying we use grpc. Proto over http is perfectly valid.
I'm against protobuf on complexity grounds, fwiw. It's an additional client-side dep. Why not multipart/form-data?

**Comment by jacksonargo** [comment]
multipart/form-data sucks. I want typed fields.

**Comment by jacksonargo** [comment]
I did multipart/form-data because browser supports that. But, we're going js client anyways, so why limit ourselves?

**Comment by 0az** [comment]
JS bundle size, and overhead.

**Comment by jacksonargo** [comment]
Nah, it's not a problem. And if it is, we can serialize with json.

**Comment by 0az** [comment]
The other reason for `multipart/form-data` is allowing us to POST the PDF and metadata in one request. I don't really want to post something with an embedded base64 string blob.

**Comment by jacksonargo** [comment]
Bruh. I hate to say. What do you think you are posting when you post multipart/form-data?

JSON, form-data, and protobuf all just ways to encode data. Form data just happens to suck the most because it barely has named fields, and has zero typing, and isn't human readable.

Json wins points for being human readable and having implied types. But it's still not structured.

Protobuf looses points for not being human readable, but otherwise has everything you need. Named fields. Strongly typed. All the models are auto-generated for you and extendable so we don't have to worry about changing data formats. You get an sdk with enums and builders for free.

**Comment by jacksonargo** [comment]
Since we're going js anyways, that means we control client and api code. We can do whatever we want, and we aren't limited by browser support. Let's take advantage of modern data tooling to make our lives easier.

**Comment by 0az** [comment]
> Bruh. I hate to say. What do you think you are posting when you post multipart/form-data?
Binary data, as per https://tools.ietf.org/html/rfc2046#section-5.1

Tested with `nc -l 8080 &; curl -F file=@$file localhost:8080`.

**Comment by jacksonargo** [comment]
_What_ is binary data? I guess at the heart of it, it's just a 1's and 0's right? But it's represented in a specific way, by its encoding. 

When you do a `nc -l 8080 &; curl -F file=@$file localhost:8080`, you terminal is trying to translate those 1's and 0's into utf8 encoding and print it out to you. If the file contains PDF encoded data, then it's gonna look like a mess since the 1's and 0's aren't all utf8 encoded data.

Base64 encoding has the advantage that it is all printable characters w/ no punctuation, and thus it works well in `json`. That's how binary data is represented in json.

We're trying to solve the problem that a pdf file doesn't not encode the information we need. We need to encode more data around the pdf. Again, with `curl` you are leveraging curl's tooling to convert a binary file into something that can be encoded in multi-part form data. But, _we_ dont have to use curl here. In fact, we _wont_ be using curl here, because it alone isn't enough to encode the data in a useful way.

**Comment by jacksonargo** [comment]
These are all different ways to encode data. We want the one that is easiest for us to program around.
```
$ curl -F file=@$file localhost:8080/snake-eater/trumpet/1
$ curl -F file=@$file localhost:8080/snake-eater/trumpet,tuba/1,3
$ curl -F file=@$file localhost:8080?project=snake-eater&instrument=trumpet&instrument=tuba&part_number=1&partnumber=3
$ vvgo-serializer -file Trumpet 1 [trumpet, 1].pdf | curl localhost:8080/uploads
$ curl localhost:8080/uploads < my_data.json
```

**Comment by jacksonargo** [comment]
For uploading from the cmdline, this would be the ideal program. No guess work, tells you how to use it, and does all the heavy-lifting for you. 
```
$ vvgo-uploader --help
Uploads files to vvgo
$ vvgo-uploader *.pdf
```

**Comment by jacksonargo** [comment]
I'm going to continue on with json, since it's the simplest option rn. Once we get to a point where were building the js client, switching to protobuf might make more sense. But, no need to optimize where it isn't needed yet.
