### ISSUE TITLE
Cross-check ValidPartNames.txt with MuseScore's instruments.xml file

### ISSUE THREAD

**Issue by Ranzha** [virtual-vgo/vvgo#74]
I encountered a rather heartbreaking issue during archival for Snake Eater: MuseScore's program supports the instrument "Shaker", but doesn't include a listing for it on their website's instrument index.
Since we copypasta'd the instrument index, there may be more inconsistencies between what MuseScore's program supports and what they list on their website. This may also lead to naming issues.
I've sent off a list of instruments from MuseScore 3.4.2 to Jackson, who is issuing a PR to "union" the two lists (ValidPartNames.txt and MuseScore 3.4.2's instrument list) together.

For reference, the most up-to-date version of instruments.xml is [here](https://github.com/musescore/MuseScore/blob/master/share/instruments/instruments.xml), but the code for the latest public release is [here](https://github.com/musescore/MuseScore/blob/3.4.2/share/instruments/instruments.xml).

**Comment by 0az** [comment]
Merged #75, closing.
