### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by jacksonargo** [virtual-vgo/vvgo#8]

**Comment by Ranzha** [comment]
In particular, what should authentication be needed for when it comes to the site? If we can authenticate users through Discord (and their roles!), this could become simple.

A few things come immediately to mind:
- View /sheets: any VVGO Member.
- Upload: VVGO Leader/Organizer, Rep/Prep team, Tech team.
- Download current project materials from /sheets: any VVGO member.
- Download past Project #XX materials from /sheets: any user with Discord role "Arch. S. #XX project" (or whatever).

**Comment by 0az** [comment]
Merged: Basic Auth (#26)

**Comment by 0az** [comment]
> In particular, what should authentication be needed for when it comes to the site? If we can authenticate users through Discord (and their roles!), this could become simple.
> 
> A few things come immediately to mind:
> 
>     * View /sheets: any VVGO Member.
> 
>     * Upload: VVGO Leader/Organizer, Rep/Prep team, Tech team.
> 
>     * Download current project materials from /sheets: any VVGO member.
> 
>     * Download past Project #XX materials from /sheets: any user with Discord role "Arch. S. #XX project" (or whatever).

I should note, this is more *authorization* than authentication.

Request for Comments (based on out of band prototyping):

- Shunt authentication and authorization to a separate service.
	- Partial prototype written in Python, can rewrite in Go later.
- Identify users using Discord Snowflake
	- Advantage: Discord as Source of Truth
	- Disadvantage: Dependency on Discord
- Authenticate users by using Discord `/users/@me` route.
	- Requires Discord OAuth2 `identify` route
	- Persist Authenticity using a JWT with a `x-discord-user-id` claim. This MUST be stored as a string.
- Authorize users by using a single OAuth2 `bot` scope client
	- Check against a configured role list
	- Maybe just return a signed, timestamped role list
- Place Auth/Login behind the ingress, location TBD

If there's any ambiguity in any of the important interface bits here, LMK.

**Comment by jacksonargo** [comment]
I think it would be simplest to keep authentication based on Discord roles for now. Other vvgo leaders are pretty comfortable using discord roles, so they would appreciate it.

I'll suggest one more option that I've done before. (Tho this might be what you had in mind for option 4). Create a chat bot that returns a temporary access link. 
1. Users ask the bot `where do I find sheet music?` 
1. The bot can query discord for their roles/etc to make sure they have correct perms. 
1. Then, the bot queries the vvgo api-server for an access token. We can provision a token that the bot uses to authenticate to the api-server. 
1. Finally, the bot return a link like `https://vvgo.org/sheets?access_token=0xff` in the discord chat.
1. When the user visits the link, the api-server can validate the access token. 

Not as elegant or secure, but we wouldn't need to worry about implementing oauth.

I think we can save `Download past Project #XX materials` for later, since we really don't have past projects yet. (I also think this is like... way unnecessary and I'll get more feed back from other leaders as to why they think this is necessary).

Whatever we choose, I'd like to keep it in golang, for deployment and integration simplicity. Altho, with docker containers, deployment complexity isn't such a big deal.

In any case, I don't really have any strong opinions here. All of these solutions seem perfectly viable, so if any jumps out at you, feel free to jump on it!

P.s. I'm ridiculously biased against python, albeit I haven't really used python3 and hear that it's much better.

**Comment by 0az** [comment]
Part of the motivation for this architecture in particular is because I need to write similar code for other projects, so structuring it this way means I can reuse essentially the entire package.

Anyway, the only thing that really needs auth are the upload endpoints, don't really see a need to gate the downloads.

> P.s. I'm ridiculously biased against python, albeit I haven't really used python3 and hear that it's much better.

PY3 *is* much better. :P

**Comment by 0az** [comment]
### RFC: Authentication State Machine Specification (informal)

---
- Unauthenticated Client
- Request Login from Login Endpoint (Reverse Proxied to Auth Service)
- Enter Discord OAuth2 Authorization Code Grant flow
	- Redirect to Discord OAuth2 endpoint
---
- Receive OAuth2 Callback with Code at Callback endpoint
- Verify grant success
- Request Token using Code from Discord Token Request endpoint
- Request `/users/@me`, authenticating with the user Token
- Create a signed JWT with a TBD claim storing the Discord User ID
	- This can later be integrated into a Refresh Token system
- Respond with 302/303/307 (TBD) redirect, setting a TBD Cookie to the signed JWT, with appropriate TBD parameters.
---
- Authenticated Client
- Make request to route requiring authentication, with the signed Cookie.
---

Note: Auth*orization* is out of scope for this RFC.
