### ISSUE TITLE
By default, sort all parts in score order on /parts

### ISSUE THREAD

**Issue by Ranzha** [virtual-vgo/vvgo#98]
There's a lot of ways this can be done, like having the user specify the order during upload or assigning weights to the parts.

For reference, our score order is below:

**Comment by jacksonargo** [comment]
## Saxophones
* Sop
* Alto
* Tenor
* Bari
##* Brass
* Horns* in* F
* Trumpets
* Trombones & Euphoniums
* Tuba
## Pitched Percussion
* Timpani
* Glock
* Vibes
* Chimes
* Xylo
* Marimba
## Unpitched Percussion
* Snare
* Bass Drum
* Tam-Tam
* Shaker
* Triangle
* Piatti (Crash Cymbals)
* Suspended Cymbal
* Tambourine
## Vocals
* Soprano
* Mezzo-soprano
* Alto
* Tenor
* Baritone
* Bass
* Vocal Percussion
## Harp and Keyboards
* Harp
* Piano
* Organ
## Guitars and Set
* Acoustic Guitar
* Electric Guitars
* Electric Bass
* Drumset
## Orchestal Strings
* Violin 1
* Violin 2
* Viola
* Violoncello
* Contrabass

**Comment by Ranzha** [comment]
## Orchestral Woodwinds
* Piccolo
* Flute 1, 2
* Oboe 1, 2
* English Horn
* Eb Clarinet
* (Bb) Clarinet 1, 2
* (Bb) Bass Clarinet
* (Bb Contrabass Clarinet)
* Bassoon 1, (2)
* Contrabassoon

## Saxophones and EWI
* (Electronic Wind Instrument)
* Soprano Saxophone
* Alto Saxophone 1, (2)
* Tenor Saxophone
* Baritone Saxophone
* (Bass Saxophone)

## Brass
* Horn in F 1, 2, 3, 4, (5, 6)
* (Horn in Eb 1, 2, 3, 4, 5, 6)
* Trumpet 1, 2, (3, 4)
* (Flugelhorn)
* (Alto Trombone)
* Trombone 1, 2, (3)
* (Bass Trombone)
* (Euphonium 1, 2, 3)
* Tuba

## Percussion
* Timpani
* Snare Drum
* Bass Drum
* Bongos
* Congas
* Suspended Cymbal
* Piatti
* Tam-tam
* Tambourine
* Triangle
* (Shaker)
* Glockenspiel
* Xylophone
* Vibraphone
* Marimba
* Chimes

## Other Instruments
### Woodwinds
* Ryūteki
* (Irish) Tin Whistle
* Low Whistle
### Free Reed
* Shō
* Melodica
* (Anglo) Concertina
* Accordion
### Zithers
* Gu Zheng
* Koto
* Kantele
### Lutes
* Liu Qin
* Gao Yin Ruan
* Zhong Ruan
* Ukulele
* Bandurria
* Mandolin
* Bouzouki
* Laúd
* Octavina
### Unpitched Percussion
* Kakko
* Bodhrán
### Pitched Percussion
* Kulintang


## Rock Band
* Acoustic Guitar
* Electric Guitar 1
* (Electric Guitar 2)
* Electric Bass
* Drumset

## Harp and Keyboards
* Harp 1
* (Harp 2)
* Piano 1
* (Piano 2)
* (Keyboard/Synthesizer)
* (Celesta)
* Organ

## Vocals
* (Solo Voice)
* Soprano 1, (2)
* (Mezzo-soprano)
* Alto 1, (2)
* (Countertenor)
* Tenor 1, (2)
* (Lead)
* (Baritone)
* Bass 1, (2)
* (Vocal Percussion)

## Bowed Strings
* Violin I
* Violin II
* Viola
* Violoncello
* Contrabass

**Comment by Ranzha** [comment]
Closed (see #163).
